### ISSUE TITLE
Fatal error: NsViewRepresentables must be value types: Representable

### ISSUE THREAD

**Issue by soundflix** [aerobounce/HoverAwareView#1]
Hi!
I have used .onHoverAwareView for more than a year. After upgrading to XCode 14.3, my new builds crash with this: 
`Fatal error: NsViewRepresentables must be value types: Representable`
point in my `NSWindow `subclass at the line
`self.contentView = NSHostingView(rootView: myView) // myView uses .onHoverAware`
It means I should use struct instead of class for `Representable`?
I can't relate any of my recent codes changes with this, it's strange.

**Comment by aerobounce** [comment]
Thanks for your report, I have pushed an update.

Yes, Representables should have always been value types, and recent versions of Xcode are now warning us about this.

**Comment by soundflix** [comment]
Here, with XCode 14.3, it didn't warn, but the app was immediately crashing with the above `Fatal error`. The same code worked fine until 14.2
Thanks for the update!
